site_name: Mkdoc Tutorials by AnkitM
site_description: A book to learn MkDocs
site_author: Ankit M
repo_url: https://github.com/ankitind/mkdocs-tutorial

nav:
    - Getting Started: getting-started.md
    - Creating Content: creating-content.md 
    - Styling Site: styling-site.md
    - Configuration: configuration.md
    - <br />markdown-cheatsheet: markdown-cheatsheet.md
    - yaml-cheatsheet: yaml-cheatsheet.md
    - github-pages: github-pages.md

theme:
    name: material

# theme: 
#     name: material
#     logo:
#         icon: star
#     favicon: img/favicon.ico
#     language: en
#     palette:
#         primary: royalblue
#         accent: yellow
#     font:
#         text: Roboto
#         code: Roboto Mono
#     feature:
#         tabs: true

markdown_extensions:
    - codehilite
    - markdown_include.include

# extra_css:
#     - extra_css.css

use_directory_urls: true