site_name: MkDocs
site_url: https://www.mkdocs.org
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Introduction: index.md
    - Deep Dive:
        - Getting Started: getting-started.md
        - Creating Content: creating-content.md 
        - Styling Site: styling-site.md
        - Configuration: configuration.md
        - Extensions & Plugins: extensions-and-plugins.md
        - Custom Theme: custom-theme.md
        - Deployment: deployment.md
        - Checklist: checklist.md
    - Cheatsheets:
        - Markdown: markdown-cheatsheet.md
        - YAML: yaml-cheatsheet.md
        - Github Pages: github-pages.md
        - Jinja 2 : jinja2-cheatsheet.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
