site_name: MkDocs
site_url: https://www.mkdocs.org
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

# theme:
#     name: mkdocs
#     highlightjs: true
#     hljs_languages:
#         - yaml
#         - django

theme:
    name: null
    custom_dir: 'custom_theme/'

nav:
    - Introduction: index.md
    - Deep Dive:
        - Getting Started: deep-dive/getting-started.md
        - Creating Content: deep-dive/creating-content.md 
        - Styling Site: deep-dive/styling-site.md
        - Configuration: deep-dive/configuration.md
        - Extensions & Plugins: deep-dive/extensions-and-plugins.md
        - Custom Theme: deep-dive/custom-theme.md
        - Deployment: deep-dive/deployment.md
        - Checklist: deep-dive/checklist.md
    - Cheatsheets:
        - Markdown: cheatsheets/markdown-cheatsheet.md
        - YAML: cheatsheets/yaml-cheatsheet.md
        - Github Pages: cheatsheets/github-pages.md
        - Jinja 2 : cheatsheets/jinja2-cheatsheet.md


markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2019, DataisGood.
# google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
